[package]
name = "b-table"
version = "0.1.0"
authors = ["code@tinychain.net"]
edition = "2021"
description = "A persistent database table based on b-tree"
license = "Apache-2.0"
readme = "README.md"
keywords = ["persistent", "ordered", "indexed", "relational", "table"]
categories = ["database", "database-implementations", "data-structures"]

[features]
stream = ["b-tree/stream"]

[[example]]
name = "example"
required-features = ["stream"]

[dependencies]
b-tree = { path = "../b-tree" }
collate = { path = "../collate" }
freqfs = { path = "../freqfs" }
futures = "0.3"
num_cpus = "1.15"
safecast = { path = "../safecast" }

[dev-dependencies]
destream = { path = "../destream" }
destream_json = { path = "../destream_json", features = ["value"] }
number-general = { path = "../number-general" }
rand = "0.8"
tokio = { version = "1.25", features = ["macros"] }
