[package]
name = "b-table"
version = "0.1.0"
authors = ["code@tinychain.net"]
edition = "2021"
description = "A persistent database table based on b-tree"
license = "Apache-2.0"
readme = "README.md"
keywords = ["persistent", "ordered", "indexed", "relational", "table"]
categories = ["database", "database-implementations", "data-structures"]

[dependencies]
b-tree = { path = "../b-tree" }
collate = { path = "../collate" }
freqfs = { path = "../freqfs" }
futures = "0.3"
safecast = { path = "../safecast" }

[dev-dependencies]
async-trait = "0.1"
bytes = "1.4"
destream = { path = "../destream" }
destream_json = { path = "../destream_json", features=["tokio-io", "value"] }
number-general = { path = "../number-general" }
rand = "0.8"
tokio = { version = "1.25", features = ["macros"] }
tokio-util = { version = "0.7", features = ["io"] }
